export var lang = {
  tc: {
    Welcome: {
      title: "閱讀新世界",
      description: "BTreader 是您在電腦上閱讀小說的最佳利器。自動的書籤紀錄讓你不怕忘記上次的閱讀進度，您也可以在利用 BTreader 閱讀線上小說。",
      button_last_read: "閱讀上次進度",
      button_local: "前往書架",
      button_online: "線上書庫",
    },
    Navbar: {
      button1: "主頁",
      button2: "書架",
      button3: "線上書庫",
      button5: "設定",
      button4: "正在閱讀",
      navTitle: "目前章節："
    },
    Library: {
      button_edit: "編輯",
      button_editDone: "完成",
      button_newLocal: "開啟",
      button_delete: "刪除",
      button_sortedby: "排序依據：",
      sort1: "加入時間",
      sort2: "閱讀順序",
      sort3: "檔案名稱",
      // noBooks: "書架上沒有書！\n您可以按上方的 開啟 按鈕來打開本地的 txt 檔案，或是到 線上書庫 點擊一本書來閱讀",
      noBooks1: "書架上沒有書！\n您可以按上方的",
      noBooks2: "開啟", 
      noBooks3: "按鈕來打開本地的 txt 檔案，或是到",
      noBooks4: "線上書庫", 
      noBooks5: "點擊一本書來閱讀",
    },
    LibraryItem: {
      author: "作者：",
      authorUnknown: "未知",
      unread: "尚未閱讀",
      currentChapter: "目前章節：",
      totalChapter1: "共 ",
      totalChapter2: " 個章節",
      lastRead: "上次閱讀：",
    },
    ChapterList: {
      title: "章節列表", 
      nochapter: "本書無任何可用章節",
    },
    Reading: {
      norecent: "沒有最近的閱讀紀錄！趕快到書架選一本書來閱讀吧！您也可以透過線上書庫來閱讀您喜歡的書。"
    },
    Setting: {
      yes: "是",
      no: "否",
      autoLoad: "自動載入上次關閉前的閱讀紀錄",
      fontSize: "字體大小",
      fontSizeTitle: "選擇字體大小",
      default: "預設",
      small: "小",
      verySmall: "很小",
      large: "大",
      veryLarge: "很大",
      superLarge: "非常大",
      lineHeight: "行高",
      language: "語言",
      systemDefault: "系統預設",
      english: "英語 english",
      tchinese: "繁體中文",
      schinese: "簡體中文 简体中文",
      fontColor: "文字䫩色",
      backgroundColor: "背景顏色",
      bctitle: "自定背景顏色",
      cancel: "取消",
      confirm: "確認",
      bcbcustom: "調色盤",
      localImage: "圖片",
      fctitle: "自定文字顏色",
      fcbcustom: "調色盤",
      previewContent: "文字大小預覽\n以及行距預覽",
      preview: "預覽",
    },
  }
}
